/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/


// src/clock.worker.ts
var clock_worker_default = "./clock.worker-CXRVMLTU.ts";
export {
  clock_worker_default as default
};
