// ARQUIVO: esbuild.config.mjs (VERSÃO FINAL COM PLUGIN DE WORKER INLINE)
import path from 'path'; // **NOVO** - Importação correta para ESM
import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import sveltePlugin from 'esbuild-svelte';
import sveltePreprocess from 'svelte-preprocess';
import findCacheDir from 'find-cache-dir';
import fs from 'fs'; // **NOVO** - Importa o módulo de sistema de arquivos

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// **INÍCIO DA MUDANÇA CRÍTICA: PLUGIN PARA INLINING DO WORKER**

// Função para compilar o worker em memória e retornar seu código como string
const buildWorker = async (workerPath) => {
    const result = await esbuild.build({
        entryPoints: [workerPath],
        bundle: true,
        format: 'esm', // Workers usam formato de módulo ES
        write: false, // Importante: não escreve no disco, retorna o conteúdo
        target: 'es2018',
    });
    return result.outputFiles[0].text;
};

// Plugin customizado do esbuild para lidar com a importação do worker
const inlineWorkerPlugin = {
    name: 'inline-worker',
    setup(build) {
// CÓDIGO CORRIGIDO E ROBUSTO
build.onResolve({ filter: /\?worker$/ }, args => {
    // Padrão de Resolução de Caminho Robusto (Node.js)
    const workerPath = path.resolve(
        path.dirname(args.importer), 
        args.path.replace('?worker', '')
    );
    
    return {
        path: workerPath,
        namespace: 'inline-worker',
        pluginData: {
            workerPath: workerPath,
        },
    };
});

        // Carrega o conteúdo para o namespace 'inline-worker'
        build.onLoad({ filter: /.*/, namespace: 'inline-worker' }, async (args) => {
            const workerCode = await buildWorker(args.pluginData.workerPath);

            // Gera o código que será injetado no main.js
            // Este código cria uma URL de Blob a partir da string do worker e exporta o construtor
            const contents = `
                export default function() {
                    const code = ${JSON.stringify(workerCode)};
                    const blob = new Blob([code], { type: 'application/javascript' });
                    const url = URL.createObjectURL(blob);
                    return new Worker(url);
                }
            `;
            
            return { contents };
        });
    },
};
// **FIM DA MUDANÇA CRÍTICA**


const baseOptions = {
    banner: {
        js: banner,
    },
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/closebrackets',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/comment',
        '@codemirror/fold',
        '@codemirror/gutter',
        '@codemirror/highlight',
        '@codemirror/history',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/matchbrackets',
        '@codemirror/panel',
        '@codemirror/rangeset',
        '@codemirror/rectangular-selection',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/stream-parser',
        '@codemirror/text',
        '@codemirror/tooltip',
        '@codemirror/view',
        ...builtins,
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
};

const mainOptions = {
    ...baseOptions,
    entryPoints: ['src/main.ts'],
    outfile: 'main.js',
    plugins: [
        sveltePlugin({
            preprocess: sveltePreprocess(),
            compilerOptions: {
                dev: !prod,
                css: 'injected',
            },
        }),
        // **NOVO** - Adiciona nosso plugin customizado à lista de plugins do esbuild
        inlineWorkerPlugin,
    ],
};

(async () => {
    try {
        if (prod) {
            await esbuild.build(mainOptions);
        } else {
            const mainCtx = await esbuild.context(mainOptions);
            await mainCtx.watch();
            console.log('esbuild is watching for changes...');
        }
    } catch (e) {
        console.error(e);
        process.exit(1);
    }
})();